#include <stdint.h>

typedef struct {
	uint32_t* pixels;
	uint16_t canvas_w;
	uint16_t canvas_h;
} RenderContext;

typedef float (*PreFrameCallback)(void *self);
typedef void (*PostFrameCallback)(void *self);
typedef void (*UpdateFn)(void *self, float dt);
typedef void (*InitFn)(void *self);
typedef void (*DrawFn)(void *self, RenderContext ctx);
typedef void (*RemoveFn)(void *self);

typedef struct {
	int id; // Generated by engine upon addition.
        InitFn  c_init;
        UpdateFn c_update;
        DrawFn c_draw;
        RemoveFn c_remove;
        bool queueFree;
        void* data;
} Entity;

typedef struct {
    PreFrameCallback preframe;
    PostFrameCallback postframe;
    Entity* entities;
    int capacity;
    int entity_count;
    int id_counter;
} Engine;

Engine FE_InitEngine(PreFrameCallback pre_frame, PostFrameCallback post_frame);
void FE_DestroyEngine(Engine* engine);
void FE_Loop(Engine* engine, RenderContext ctx);
void FE_Free(Engine* engine);

int FE_AddEntity(Engine* engine, Entity e);
void FE_RemoveEntity(Engine* engine, int id);
