#include <stdint.h>
#include <stdbool.h>

#define INPUT_BUFFER_SIZE 16
#define N_AUDIO_STREAMS 16

typedef struct {
	uint32_t* pixels;
	uint16_t canvas_w;
	uint16_t canvas_h;
} RenderContext;

typedef struct {
    float* frames;
    int n_samples;
} AudioStream;

typedef struct {
    AudioStream streams[N_AUDIO_STREAMS];
    float* output;
    float t;
    int sample_rate;
} AudioContext;

typedef struct {
    char key;
    bool down; 
} InputEvent;

typedef struct {
    InputEvent events[INPUT_BUFFER_SIZE];
    uint8_t event_counter;
    uint8_t mouseButton;
    int mouseX;
    int mouseY;
} Input;

typedef float (*PreFrameCallback)(void *self);
typedef void (*PostFrameCallback)(void *self, RenderContext rctx, AudioContext actx);
typedef void (*UpdateFn)(void *self, Input input, float dt);
typedef void (*InitFn)(void *self);
typedef void (*DrawFn)(void *self, RenderContext ctx);
typedef void (*AudioFn)(void *self, AudioContext ctx);
typedef void (*RemoveFn)(void *self);

typedef struct {
	int id; // Generated by engine upon addition.
    InitFn  c_init;
    UpdateFn c_update;
    DrawFn c_draw;
    AudioFn c_audio;
    RemoveFn c_remove;
    bool queueFree;
    void* data;
} Entity;

typedef struct {
    PreFrameCallback preframe;
    PostFrameCallback postframe;
    Input input;
    Entity* entities;
    int capacity;
    int entity_count;
    int id_counter;
    float dt;
} Engine;

Engine FE_InitEngine(PreFrameCallback pre_frame, PostFrameCallback post_frame);
void FE_DestroyEngine(Engine* engine);
void FE_Loop(Engine* engine, RenderContext rctx, AudioContext actx);
void FE_Free(Engine* engine);

int FE_AddEntity(Engine* engine, Entity e);
void FE_RemoveEntity(Engine* engine, int id);
